### ISSUE TITLE
Add ArcGIS Maps SDK for JavaScript

### ISSUE THREAD

**Issue by ggfevans** [joewdavies/awesome-frontend-gis#6]
[ArcGIS Maps SDK for JavaScript](https://developers.arcgis.com/javascript/latest/) - Modern JavaScript API and web component library for building interactive web apps for the browser.

**Comment by joewdavies** [comment]
Done https://github.com/joewdavies/awesome-frontend-gis/commit/5ca38582a93103ffc8d0fcc6a895283f3ab089c6
