### ISSUE TITLE
Remove ArcGIS API for JavaScript (legacy)

### ISSUE THREAD

**Issue by ggfevans** [joewdavies/awesome-frontend-gis#7]
Version 3.x retired on July 1st, 2024
Version 3.46 was the last version of 3.x. See the [retirement announcement](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/) for more information.

**Comment by joewdavies** [comment]
Done https://github.com/joewdavies/awesome-frontend-gis/commit/5ca38582a93103ffc8d0fcc6a895283f3ab089c6
